= Android Bootcamp Training

25 March 2014

*Marius Mailat*, +<marius.mailat@gmail.com>+
http://thewnewcircle.com[The New Circle, Inc.]

== Obtaining Course Materials

You can either clone this Git repository:

  git clone git://github.com/mailat/bootcamp-2014-03-24.git

or

   download a Zip archive by clicking the link at the top of the page or using the link:
  
	https://github.com/mailat/bootcamp-2014-03-24/zipball/master

== Useful Links

Git book: http://git-scm.com/book

Marakana Java Fundamentals Tutorial: http://marakana.com/bookshelf/java_fundamentals_tutorial/index.html

Introduction to Eclipse - Driving Java Productivity: http://mrkn.co/s/video_introduction_to_eclipse_driving_java_productivity,595/index.html

Java Tutorial http://docs.oracle.com/javase/tutorial/

== Homework Day 01

- Post the text from the EditText and NOT the hardcoded one
- For bonus points: add a ProgressDialog!

== Homework Day 02

- Prepare the "wish app" you want to see on Friday!
- Create a new Activity named: FakePreferenceActivity.java (extending Activity) with the purpose of replacing the PrefsActivity. Tips:
1. create a new layout names fake_prefs_activty.xml
2. add in the layout 2 TextView-s and 2 EditText
3. read the values from the EditText and save them using SharedPreferences 

== Homework Day 03

- create a broadcast receiver who stops the service in case you are in roaming and start the service once you are back from roaming
